-- CLEAN TABLES

-- VARIANT MODEL DELETIONS
DELETE FROM VARIANT_FEATURE;
DELETE FROM VARIANT_CODE;
DELETE FROM VARIANT_COMPONENT;
DELETE FROM VARIANT_MODEL;

-- FAMILY MODEL DELETIONS
DELETE FROM VARIATION_POINT_FEATURE;
DELETE FROM CODE_VARIATION_POINT;
DELETE FROM VARIATION_POINT;
DELETE FROM CODEFILE;
DELETE FROM PART;
DELETE FROM DIRECTORY;
DELETE FROM CODE_ELEMENT;

-- FEATURE MODEL DELETIONS
DELETE FROM FEATURE_SIZE;
DELETE FROM DEPENDENCY;
DELETE FROM ATTRIBUTE;
DELETE FROM FEATURE;
DELETE FROM FEATURE_MODEL;

-- SPL DELETION
DELETE FROM SPL;


-- DROP TABLES

/*

DROP TABLE VARIANT_FEATURE;
DROP TABLE VARIANT_CODE;
DROP TABLE VARIANT_COMPONENT;
DROP TABLE VARIANT_MODEL;

-- FAMILY MODEL DELETIONS
DROP TABLE VARIATION_POINT_FEATURE;
DROP TABLE CODE_VARIATION_POINT;
DROP TABLE VARIATION_POINT;
DROP TABLE CODEFILE;
DROP TABLE PART;
DROP TABLE DIRECTORY;
DROP TABLE CODE_ELEMENT;

-- FEATURE MODEL DELETIONS
DROP TABLE FEATURE_SIZE;
DROP TABLE DEPENDENCY;
DROP TABLE ATTRIBUTE;
DROP TABLE FEATURE;
DROP TABLE FEATURE_MODEL;

-- SPL DELETION
DROP TABLE SPL;

*/
