DELETE FROM RESOURCE;
DELETE FROM FEATURE_LINK_ELEMENT;
DELETE FROM CONNECTION;
DELETE FROM CONCEPT;
DELETE FROM LINKING_PHRASE;
DELETE FROM LINK_ELEMENT;
DELETE FROM CMAP;

/*
DROP TABLE RESOURCE;
DROP TABLE FEATURE_LINK_ELEMENT;
DROP TABLE CONNECTION;
DROP TABLE CONCEPT;
DROP TABLE LINKING_PHRASE;
DROP TABLE LINK_ELEMENT;
DROP TABLE CMAP;
*/